#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
oauth_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController